export const Env = {
	GOOGLE_IOS_CLIENT_ID: process.env.EXPO_PUBLIC_GOOGLE_IOS_CLIENT_ID || "",
	GOOGLE_WEB_CLIENT_ID: process.env.EXPO_PUBLIC_GOOGLE_WEB_CLIENT_ID || "",
	GOOGLE_ANDROID_CLIENT_ID: process.env.EXPO_PUBLIC_GOOGLE_ANDROID_CLIENT_ID || "",

	GITHUB_MOBILE_CLIENT_ID: process.env.EXPO_PUBLIC_GITHUB_MOBILE_CLIENT_ID || "",
	GITHUB_MOBILE_CLIENT_SECRET: process.env.EXPO_PUBLIC_GITHUB_MOBILE_CLIENT_SECRET || "",
	GITHUB_WEB_CLIENT_ID: process.env.EXPO_PUBLIC_GITHUB_WEB_CLIENT_ID || "",
	GITHUB_WEB_CLIENT_SECRET: process.env.EXPO_PUBLIC_GITHUB_WEB_CLIENT_SECRET || "",

	FIREBASE_API_KEY: process.env.EXPO_PUBLIC_FIREBASE_API_KEY || "",
	FIREBASE_AUTH_DOMAIN: process.env.EXPO_PUBLIC_FIREBASE_AUTH_DOMAIN || "",
	FIREBASE_PROJECT_ID: process.env.EXPO_PUBLIC_FIREBASE_PROJECT_ID || "",
	FIREBASE_STORAGE_BUCKET: process.env.EXPO_PUBLIC_FIREBASE_STORAGE_BUCKET || "",
	FIREBASE_MESSAGING_SENDER_ID: process.env.EXPO_PUBLIC_FIREBASE_MESSAGING_SENDER_ID || "",
	FIREBASE_APP_ID: process.env.EXPO_PUBLIC_FIREBASE_APP_ID || "",
};
